[package]
name = "exit_safely"
version = "0.3.0"
edition = "2024"
readme = "README.md"
description = "Enables exiting safely with custom exit codes while still calling `Drop` as needed. Aims for minimal magic and maximum flexibilty."
authors = ["Mike Foster <https://github.com/MusicalNinjaDad>"]
keywords = ["derive", "ExitCode", "Drop", "Termination", "CLI"]
homepage = "https://github.com/MusicalNinjaDad/exit_safely"
repository = "https://github.com/MusicalNinjaDad/exit_safely"
categories = ["development-tools", "rust-patterns"]
license = "MIT"
exclude = [".github", ".devcontainer"]
rust-version = "1.95.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.117", features = ["extra-traits"] }
try_v2 = "0.7.3"
proc-macro2 = "1.0.106"
proc_macro2_diagnostic = {version = "0.6.0", git = "https://github.com/MusicalNinjaDad/proc_macro2_diagnostic", branch = "traits"}
quote = "1.0.45"

[dev-dependencies]
escargot = "0.5.15"
trybuild = "1.0.116"

[workspace]
members = ["tests/fixtures/*"]

[workspace.dependencies]
exit_safely = { path = "."}
