name: Monthly stability checks

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  schedule:
    - cron: '0 3 6 * *'

permissions:
  contents: read
  issues: write

env:
    CARGO_TERM_COLOR: always

jobs:
  
  channels:
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.strategy.outputs.strategy }}
    steps:
    - uses: actions/checkout@v7.0.0
    - name: install jaq
      uses: taiki-e/install-action@v2.81.10
      with:
        tool: jaq
    - name: process strategy
      id: strategy
      run: echo "strategy=$(jaq -c .full .github/workflows/.config/matrix.yml)" >> $GITHUB_OUTPUT

  test:
    needs:
      - channels

    strategy: ${{ fromJson(needs.channels.outputs.strategy) }}
    env:
      RUSTC_BOOTSTRAP: ${{ matrix.bootstrap }}

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v7.0.0
    - run: rustup install --profile default ${{ matrix.channel }}
    - name: Run tests
      run: cargo +${{ matrix.channel }} test --no-fail-fast

  lint:
    needs:
      - channels

    strategy: ${{ fromJson(needs.channels.outputs.strategy) }}
    env:
      RUSTC_BOOTSTRAP: ${{ matrix.bootstrap }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0
    - run: rustup install --profile default ${{ matrix.channel }}
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  report:
    if: ${{ always() }}
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - name: Create issue on failure
      if: ${{ github.event_name != 'pull_request' && (needs.test.result == 'failure' || needs.lint.result == 'failure') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create --title "Monthly tests failed" --body "Run ID: $GITHUB_RUN_ID" --assignee "MusicalNinjaDad"
